### ISSUE TITLE
[Feature]: Add Folia

### ISSUE THREAD

**Issue by Cartrigger** [jrbudda/Vivecraft_Spigot_Extensions#113]
# Why Do you Want This Feature?
Over the past year, a new sever software named Folia has come into testing stages, created by PaperMC it does multithreading much better than any non Regionalized Multithreading server software, like its said, its used for Skyblock, SMPs and the main thing for many users of the software, events that have thousands online at one time. It would be great to start supporting Folia, I do not know much about porting to non main threaded operations and things that are not included in Folia, it would be good to look into it at least.
https://papermc.io/software/folia 

I am hoping to see this implemented for VR events mostly and SMPs.

**Comment by Cartrigger** [comment]
Current issue with folia

```
[02:39:24 ERROR]: Error occurred while enabling Vivecraft-Spigot-Extensions v1.20.6-1 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[?:?]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) ~[?:?]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[?:?]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:206) ~[?:?]
        at Vivecraft_Spigot_Extensions-1.20.6-1.jar/org.vivecraft.VSE.onEnable(VSE.java:183) ~[Vivecraft_Spigot_Extensions-1.20.6-1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:632) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:581) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:717) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:464) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:350) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by fayer3** [comment]
some things in vivecraft rely on being on the main thread, or at least on the same one the server player is processed.
for example the roomscale bow needs that

**Comment by Cartrigger** [comment]
Alright it looks like CJCrafter did it

**Comment by fayer3** [comment]
I'm unsure if that will actually work right

**Comment by fayer3** [comment]
yeah, it doesn't handle the packets right

**Comment by thejudge156** [comment]
Mind clarifying what you mean? I tested it and it worked alright.

**Comment by fayer3** [comment]
throws errors when shooting bows, about not using async teleport

**Comment by Cartrigger** [comment]
yeah your right

**Comment by CJCrafter** [comment]
fixed that, my bad... issue was that the old teleport method is completely unsupported on folia. Added an API to use the correct one depending on the server

**Comment by fayer3** [comment]
arrows don't throw errors anymore, still don't work right though.
they shoot where you aim at, but the intital arrow faces in the direction your draw arm points at, and tarrows still spawn at the face

**Comment by CJCrafter** [comment]
Do you mean that the arrow spawns in the face, but then gets teleported ~100ms later to the correct position? So there is some sort of visual flash that is annoying and breaks immersion? That can be hard to fix without a packet listener to cancel outgoing entity meta packets... Let me know and I'll investigate a solution

**Comment by fayer3** [comment]
no, it just doesn't use the correct spawn position
